# Generated by Django 5.2 on 2025-12-05 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('day_of_the_year', models.IntegerField()),
            ],
            options={
                'ordering': ['year', 'day_of_the_year'],
                'constraints': [models.UniqueConstraint(fields=('year', 'day_of_the_year'), name='unique_date'), models.CheckConstraint(condition=models.Q(('day_of_the_year__gte', 1), ('day_of_the_year__lte', 365)), name='days_range_constraint', violation_error_message='days must be in range 1-365')],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('current_date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='space_calendar.gamedate')),
            ],
            options={
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='space_calendar.campaign')),
                ('game_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='space_calendar.gamedate')),
            ],
        ),
    ]
