# Generated by Django 5.0.1 on 2024-01-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hireling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dei', models.SmallIntegerField(verbose_name='DEI')),
                ('primary_skills', models.CharField(max_length=100)),
                ('secondary_skills', models.CharField(blank=True, max_length=100)),
                ('cost', models.IntegerField(verbose_name='hire cost')),
                ('gear', models.CharField(blank=True, max_length=50)),
                ('is_alive', models.BooleanField(default=True)),
                ('notes', models.TextField()),
            ],
        ),
    ]
