# Generated by Django 6.0.6 on 2026-06-10 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='sector name')),
            ],
        ),
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('base_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='base cost, kCr')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='planet name')),
                ('planet_coordinates', models.CharField(blank=True, max_length=4)),
                ('wiki_link', models.TextField(blank=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.mapsector')),
            ],
        ),
        migrations.CreateModel(
            name='PlanetWare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(300)], verbose_name='purchase price, %')),
                ('sell_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(400)], verbose_name='sell price, %')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='planets.planet')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='planets.ware')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('planet', 'ware'), name='unique_wares_for_planets'), models.CheckConstraint(condition=models.Q(('purchase_price__isnull', False), ('sell_price__isnull', False), _connector='OR'), name='purchase_or_sell_price_check', violation_error_message='At least one of the prices should be filled')],
            },
        ),
    ]
