# Generated by Django 5.0.7 on 2024-07-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_alter_ware_options_ware_base_price_ware_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='sector name')),
            ],
        ),
    ]
