# Generated by Django 5.0.7 on 2024-07-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_mapsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planets.mapsector'),
            preserve_default=False,
        ),
    ]
