# Generated by Django 5.0.1 on 2024-01-31 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetware',
            name='purchase_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(300)], verbose_name='purchase price, %'),
        ),
        migrations.AlterField(
            model_name='planetware',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(400)], verbose_name='sale price, %'),
        ),
    ]
