# Generated by Django 5.0.1 on 2024-01-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planet_economy', '0002_alter_planetware_purchase_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planetware',
            name='purchase_or_sell_price_check',
        ),
        migrations.AddConstraint(
            model_name='planetware',
            constraint=models.CheckConstraint(check=models.Q(('purchase_price__isnull', False), ('sale_price__isnull', False), _connector='OR'), name='purchase_or_sell_price_check', violation_error_message='At least one of the prices should be filled'),
        ),
    ]
